modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="the_jonkler"
version="0.3.0"
displayName="the jonkler"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Ivano, PastyRat,"
description="A mod that adds the jonkler and related brainrot items."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.the_jonkler]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration